Drobert fetch intra
pulgamecanica/42Portfolio pull request #48
Opened 2023-07-23 08:58 UTC by PukieDiederik

This implements a command `sync_db` (with sub commands) which will fetch data from the 42 API and save it in our database.
The subcommands are the following:
- `user`
- `skill`
- `project`
- `cursus`
- `relations` - Updates all the relations in the database
- `all` - Runs the commands above

There is also a new module for fetching data from the 42 api. Its split into 2 classes (although the `AuthApi42` should not really be used at the user end): `AuthApi42` & `Api42`. Api42 is our interface for the user. This has a get command which will fetch data from the api using the `GET` request method.

The `models.py` file also got some improvements. Every model now has a `__str__` & `update` functions. For the models that already had a `__str__` function, they have been updated to be a more uniform in style. The update function updates/creates a model based on json data (What we got from the api).

Our command uses the `logging` (built-in) library. This will output to a logfile (unless told otherwise by the `--no-logfile` option) and the console. The output can be changed using the (built-in) `-v` option.

This should hopefully resolve the following issue(s):
- #21
- #47 (We now use our own implementation)

2023-07-23 21:28 UTC, pulgamecanica commented
User Not Found, Cursus not found, anything not found should not fail.

Credentials invalid should not fail.

Tomorrow I'll write exactly what I mean, I just wanted to leave this here to not forget to review that .

2023-07-24 19:08 UTC, pulgamecanica requested changes
Its an absolute masterpiece I like the coding style and overall it's a very well done job.

I  left some comments among the most important things to review are:

- Encapsulation and advanced python concepts
- PEP8 naming conventions for Class attributes and Class instance attributes
- Review a little typo I found `all ==> filter`
- Find out what response we get with 500 so we can handle it correctly
- Discuss inheritance, pros and cons, consider this possibility 

We should schedule a meeting to discuss this amazing progress ;)
GL! Keep it up  :clinking_glasses:

2023-07-24 19:08 UTC, pulgamecanica commented on backend/portfolio42_api/models.py
I guess this is what u say about tabs and spaces...?

2023-07-24 19:19 UTC, PukieDiederik commented on backend/portfolio42_api/management/api42/api42.py
> +        self.__window = [] # Will store when a request expires (aka datetime.now() + 1 second)
I will update this comment to be more clear. But for now, this refers to that we are rate limited by the second. So a request should stay inside the window for 1 second (before it expires from the window).

2023-07-24 19:21 UTC, PukieDiederik commented on backend/portfolio42_api/management/api42/api42.py
> +    def wait(self, should_wait : bool):
Im not really familiar with python's decorators. I will look into this!

2023-07-24 19:22 UTC, PukieDiederik commented on backend/portfolio42_api/management/api42/api42.py
> +            self.__window = [t for t in self.__window if now < t]
I remember having this for a reason (probably because I used it somewhere else), but that reason seems to not exist anymore. I will remove this.

2023-07-24 19:25 UTC, PukieDiederik commented on backend/portfolio42_api/management/api42/api42.py
> +            raise RuntimeError(res.json()['error_description'])
I can guarantee that not every response returns a json (Like 429 return `Too Many Requests` in the body). I will update this with a try-except.

2023-07-24 19:27 UTC, PukieDiederik commented on backend/portfolio42_api/management/api42/api42.py
> +class Api42():
The way I see it is that inheritance has a `is a` relationship (example: `sheep` `is an` `animal`). And Api42 is not a form of 42 authentication.

2023-08-26 19:32 UTC, PukieDiederik commented
Made the changes that you suggested.

2023-08-28 10:40 UTC, pulgamecanica commented
We should add to our wiki how the commands work, do you want to take over that? I can also do it, let me know 🗡️

2023-08-28 11:26 UTC, pulgamecanica requested changes
Awesome work, I am glad to see that you've progressed so much, I think this will help you a lot for the future, and working with Python is always a nice experience.

We just need to polish 💅 everything and it will be good to merge! ⏫

2023-08-29 10:33 UTC, pulgamecanica approved these changes
Awesome! It's looking very nice.

We can discuss how to setup cron with docker later ;D
So it can run daily or once every two days.

We want to mention this with Vitor, so we have clear objectives for the next evaluation.

Cheers, happy summer! 🏖️

2023-08-29 10:34 UTC, merged